"""add phone number

Revision ID: 45cbc279a53d
Revises: 63d9f31c7bf6
Create Date: 2022-08-17 15:36:01.146355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cbc279a53d'
down_revision = '63d9f31c7bf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('publish', sa.Boolean(), server_default='TRUE', nullable=False))
    op.drop_column('posts', 'published')
    op.add_column('users', sa.Column('phone_number', sa.Integer(), nullable=False))
    op.drop_constraint('votes_post_id_fkey', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'users', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_post_id_fkey', 'votes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'phone_number')
    op.add_column('posts', sa.Column('published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('posts', 'publish')
    # ### end Alembic commands ###
